# src/main/resources/META-INF/mods.toml

modLoader="javafml"
loaderVersion="[41,)"      # Forge loader 41+ (fits 1.19.2)
license="All rights reserved"

[[mods]]
modId="gokumod"
version="1.0.0"
displayName="Goku Gear Mod"
authors="Awais"
description='''
Integrates MUI Goku custom armor and attacks into a Tensura-based modpack,
with models, animations, damage effects, and sound.
'''

[[dependencies.gokumod]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"

[[dependencies.gokumod]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"
